<?php

function sasi_home_menu(){
  $items['sasi/run_sasi'] = array(
    'title' => 'Run SASI',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sasi_home_run_sasi_form'),
    'access callback' => true,
    'description' => 'Run SASI Form',
    'file' => 'run_sasi_form.inc'
  );
  return $items;
}

/**
 * Callback handler for when run_sasi tasks complete.
 * Will receive task node as an argument.
 */
function sasi_home_run_sasi_task_completed($node){
  watchdog('debug', 'garbanzon!');
  // Get project id from task data.
  $task_array = xtasks_task_to_array($node);
  $project_id = $task_array['data']['project_id'];
  $node->title = "Flagroato";
}
